name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 5. Configurar credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 1. Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configuración de Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Install Amplify CLI
        run: |
          npm install -g @aws-amplify/cli

      # 3. Instalar dependencias
      - name: Instalar las dependencias
        run: |
          npm install

      # 4. Correr build
      - name: Correr build
        run: |
          npm run build

      # 5. Subir la carpeta build a S3
      - name: Subir la carpeta build a S3
        run: |
          aws s3 cp build/ s3://${{ secrets.AWS_S3_BUCKET }}/build/ --recursive

      # 7. Crear aplicación Amplify usando la carpeta build desde S3
      - name: Crear y desplegar aplicación Amplify
        run: |
          # Crear un nuevo proyecto Amplify
          amplify init --yes

          # Agregar hosting de Amplify con S3 y CloudFront
          amplify add hosting \
            --hosting-name my-app-hosting \
            --bucket-name ${{ secrets.AWS_S3_BUCKET }} \
            --index-document index.html \
            --error-document error.html

          # Desplegar la aplicación
          amplify publish --yes
